base_url = "https://blog.choco14t.net"
title = "blog.choco14t.net"
description = "blog.choco14t.net"
default_language = "ja"
compile_sass = true
generate_feeds = true
feed_filenames = ["rss.xml"]

[markdown.highlighting]
enabled = true
theme = "Nord"

[[taxonomies]]
name = "tags"

[extra]
author = "choco"
google_analytics_id = "G-CJJ2ER4EPC"
