name: textlint

on:
  pull_request:
    branches:
      - main

defaults:
  run:
    working-directory: ./

jobs:
  textlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: 18

      - uses: pnpm/action-setup@v2
        with:
          version: 10.4.1

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - uses: actions/cache@v3
        name: Setup pnpm cache
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install modules
        run: pnpm install

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v39

      - name: Run textlint
        run: pnpm textlint ${{ steps.changed-files.outputs.all_changed_files }}

