name: textlint

on:
  pull_request:
    branches:
      - main

defaults:
  run:
    working-directory: ./

jobs:
  textlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      - id: node_modules_cache_id
        uses: actions/cache@v3
        env:
          cache-name: cache-node-modules
        with:
          path: '**/node_modules'
          key: ${{ runner.os }}-build-${{ env.cache-name }}-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-build-${{ env.cache-name }}-
            ${{ runner.os }}-build-
            ${{ runner.os }}-

      - name: Install modules
        if: ${{ steps.node_modules_cache_id.outputs.cache-hit != 'true' }}
        run: yarn install

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v39

      - name: Run textlint
        run: yarn textlint ${{ steps.changed-files.outputs.all_changed_files }}

